"use strict";
(function(){
const $=s=>document.querySelector(s);
function dataSize(data){return Math.ceil((data.length-(data.indexOf(',')+1))*3/4)}
function loadImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('사진을 읽지 못했습니다.'))};img.src=url})}
function canvasData(img,maxW,maxH,quality){const ratio=Math.min(1,maxW/img.naturalWidth,maxH/img.naturalHeight),w=Math.max(1,Math.round(img.naturalWidth*ratio)),h=Math.max(1,Math.round(img.naturalHeight*ratio)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);return canvas.toDataURL('image/webp',quality)}
async function optimize(file){const img=await loadImage(file);let maxW=1920,maxH=1080,quality=.84,data=canvasData(img,maxW,maxH,quality);while(dataSize(data)>900*1024&&quality>.58){quality-=.08;data=canvasData(img,maxW,maxH,quality)}if(dataSize(data)>900*1024){maxW=1600;maxH=900;data=canvasData(img,maxW,maxH,.68)}return{data,original:file.size,optimized:dataSize(data)}}
const photo=$('#photoInput'),drop=$('#photoDrop');let info=document.createElement('small');info.id='imageOptimizeInfo';info.style.cssText='display:block;margin-top:7px;color:#6f6b74';drop.parentElement.appendChild(info);
photo.onchange=async e=>{const file=e.target.files&&e.target.files[0];if(!file)return;info.textContent='사진 최적화 중…';photo.disabled=true;try{const result=await optimize(file);active().image=result.data;info.textContent=`자동 최적화 완료: ${(result.original/1048576).toFixed(1)}MB → ${(result.optimized/1048576).toFixed(2)}MB`;render()}catch(error){info.textContent='오류: '+error.message}finally{photo.disabled=false;e.target.value=''}};
$('#autoDeploy').onclick=async()=>{const button=$('#autoDeploy'),status=$('#deployStatus');button.disabled=true;status.textContent='완성본 용량 검사 중…';try{const token=localStorage.getItem('soop_auth_token')||'';if(!token)throw new Error('기존 SOOP 효과 생성기에 먼저 로그인해주세요.');const html=storyDocumentV2(),size=new Blob([html]).size;if(size>12*1024*1024)throw new Error(`완성본이 ${(size/1048576).toFixed(1)}MB입니다. 사진 수를 줄이거나 더 작은 사진을 사용해주세요.`);status.textContent=`${(size/1048576).toFixed(1)}MB · GitHub에 업로드 중…`;const response=await fetch('https://soop-effect-api.wr7881.workers.dev/deploy',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({html,ratio:'16/9'})});let result;try{result=await response.json()}catch{throw new Error(`서버 응답 오류 (${response.status})`)}if(!response.ok||!result.ok)throw new Error(result.error||`업로드 실패 (${response.status})`);$('#storyUrl').value=result.publicUrl||'';$('#iframeCode').value=result.iframeCode||`<iframe src="${result.publicUrl}" width="100%" style="width:100%;aspect-ratio:16/9;border:0;display:block" scrolling="no" frameborder="0"></iframe>`;status.textContent=`업로드 완료! 완성본 ${(size/1048576).toFixed(1)}MB`}catch(error){status.textContent='오류: '+(error.message==='Failed to fetch'?'서버에 연결하지 못했습니다. 사진이 너무 크거나 네트워크가 차단됐습니다.':error.message)}finally{button.disabled=false}};
})();
